These are pretty well ordered by dependency.
* TODO voices: improve representation
LedBecause: maybe don't distinguish between keys and sustain,
  just use VoiceId
stFingers :: Map (X,Y) VoiceId
stSustained :: S.Set VoiceID
* TODO redraw the whole screen often
** why
Dropped messages to LEDs stop being a (hypothetical) problem.
Shading on both monomes becomes easier.
* TODO add tests
* TODO create voices on the fly
** Vivid: voice creation, use and deletion
use "synth" to make a synth, "free" to free it:
  s <- synth boop
  set s (toI f :: I "amp")
  free s
* TODO sustained pitches should not disable keys after spatial drift
Currently, because each voice is identified with a key,
if that voice is sustained, that key cannot sound a new note,
even when it no longer represents the same pitch.
* TODO flash the anchor
* TODO sustain: two buttons, "add these" and "release all"
"add these" stays in effect until it is released.
"release all" works as soon as it's touched; holding on it does nothing.
* Montevideo - Monome Tidal Vivid
** Things to represent on the monome
synth param
rhythm
chord
melody
* TODO maybe
** sustain to middle of bottom, and duplicate at both top corners
 so that usually something can touch it
* features
** show sustained notes
** add to ongoing sustained group
** transpose ongoing notes
** save to chord bank from sustain
** sustained voices do not block keys
** sustain these and future
This is what most piano sustain pedals do.
** loop bank
** volume control for sustained notes
** timbre
** split keyboard
** reset buttons
*** silence all voices
*** redraw entire grid
*** restore shift to 1
to remove floating point error
* separate projects
** separate Vivid.Jbb from Vivid
 this will make starting the repl faster
** separate my own Vivid projects
*** namely these
Vivid (clone, for reference)
Vivid.Synths.Jbb
Vivid.Dispatch
Monome
*** use symlinks between them as needed
e.g. from Monome to Synths
