* git branch structure
master -> ledRelay: done
master -> enharmonicLeds -> topLeftOrigin
  that is, before finishing enharmonicLeds, I'm taking a break to put the origin where it belongs
* TODO interrupting : fix the typef of `voices` and `sustained`
voices should be dynamic
  if they are indexed instead by (X,Y), then the meaning of "sustained"
  becomes muddy
sustained should be a set of Pitches, not (X,Y)
dependentPitchClass should not exist
* TODO ongoing : redraw everything upon shift
There is a bad interaction between the keyboard and shift.
If I play a chord, shift the board, then release the chord, the LEDs stay lit. They move appropriately during the shift, though.

It should be that when I release a key, I search for any pitch it is responsible for.

I need a new data field. I have one with pitchlass keys and xy values; I need one with xy keys and pitchclass values.
* maybe Led and Switch should be synonyms for Bool
so that I can call not on them, or condition on them
* features
** show sustained notes
** add to ongoing sustained group
** transpose ongoing notes
** save to chord bank from sustain
** sustained voices do not block keys
** sustain these and future
This is what most piano sustain pedals do.
** loop bank
** timbre
** split keyboard
** reset buttons
*** silence all voices
*** redraw entire grid
*** restore shift to 1
to remove floating point error
* separate projects
** separate Vivid.Jbb from Vivid
 this will make starting the repl faster
** separate my own Vivid projects
*** namely these
Vivid (clone, for reference)
Vivid.Synths.Jbb
Vivid.Dispatch
Monome
*** use symlinks between them as needed
e.g. from Monome to Synths
