* architecture
** ? windows are currently switch-aware but LED-unaware
** state
*** which buttons are down
*** which lights are on
*** which buttons correspond to which voices
*** which voices are playing what
** behavior
Each button press is tested for which window it's in, and handled by the associated function.
After that, a new grid LED state is computed, and then the difference between it and the old one, and those changes are requested from the monome.
* refector
** playKey should be playVoice, and know nothing about sustain
* features
** sustain these and future
This is what most piano sustain pedals do.
The sustain that's programmed so far sustains only things under your fingers when you press the sustain button.
** light up enharmonics of pressed|sounding keys
** chord bank
** loop bank
** timbre
** split keyboard
** shift should move the guideposts
and maybe that window should be visible
** reset buttons
*** silence all voices
*** redraw entire grid
*** restore shift to 1
to remove floating point error
* separate projects
** separate Vivid.Jbb from Vivid
 this will make starting the repl faster
** separate my own Vivid projects
*** namely these
Vivid (clone, for reference)
Vivid.Synths.Jbb
Vivid.Dispatch
Monome
*** use symlinks between them as needed
e.g. from Monome to Synths
